CC=i686-w64-mingw32-gcc
CFLAGS=-g -c -Wall -masm=intel
LFLAGS=-shared -O0

TARGET=game_controller.dll
SOURCES=game_controller.c
OBJECTS=$(SOURCES:.c=.o)
GIT_TAG := $(shell git describe --tags --abbrev=0)

all: strongmod/version.py $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(LFLAGS) $(OBJECTS) -o $@


test: $(TARGET)
	wine python -m unittest

strongmod/version.py:
	@echo "# This file is automatically generated. Do not manually edit." > $@
	@echo "version = \"$(GIT_TAG)\"" >> $@


setup-environment:
	sudo apt-get update
	sudo apt-get install -y gcc-mingw-w64-i686 unzip

download-and-unzip-cpython:
	wget https://www.python.org/ftp/python/3.8.10/python-3.8.10-embed-win32.zip
	unzip -n python-3.8.10-embed-win32.zip
	rm python-3.8.10-embed-win32.zip

.PHONY: strongmod/version.py

