CC=i686-w64-mingw32-gcc
CFLAGS=-g -c -Wall -masm=intel
LFLAGS=-shared -O0

TARGET=game_controller.dll
SOURCES=game_controller.c
OBJECTS=$(SOURCES:.c=.o)
GIT_TAG := $(shell git describe --tags --abbrev=0)

all: strongmod/version.py $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(LFLAGS) $(OBJECTS) -o $@


test: $(TARGET)
	wine python -m unittest

strongmod/version.py:
	@echo "# This file is automatically generated. Do not manually edit." > $@
	@echo "version = \"$(GIT_TAG)\"" >> $@

.PHONY: strongmod/version.py

