name: Release

on:
  push:
    tags:
      - '*.*.*'  # Match any semantic version tag, adjust as needed

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: make setup-environment

    - name: Download and unzip python
      run: make download-and-unzip-cpython

    - name: Compile project
      run: make

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r strongmod.zip ./

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ./strongmod.zip
          
