name: Release

on:
  push:
    tags:
      - '*.*.*'  # Match any semantic version tag, adjust as needed

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      working-directory: ./strongmod
      run: make setup-environment

    - name: Download and unzip python
      working-directory: ./strongmod
      run: make download-and-unzip-cpython

    - name: Compile project
      working-directory: ./strongmod
      run: make

    - name: Zip project
      working-directory: ./strongmod
      run: make zip-project

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ./strongmod/strongmod.zip
          
